name: Go Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ['1.21']
        os: [windows]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o ./chip8-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.exe ./cmd/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chip8-exe
          path: ./chip8-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: chip8-exe
          path: ./artifacts

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: "Release notes for version ${{ github.ref_name }}"
          files: ./artifacts/chip8-windows-amd64-${{ github.ref_name }}.exe
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
